"""
Class 11 (validation family A): Gaussian-process sound speed.

Construction
------------
c_s^2(n) is generated by placing a Gaussian process on the auxiliary
(logit) variable

    phi(n) = -ln( 1/c_s^2(n) - 1 ) = ln[ c_s^2 / (1 - c_s^2) ],

    phi ~ GP( phibar(n), K(n,n') ),        c_s^2(n) = expit( phi(n) ),

so that 0 < c_s^2 < 1 holds for EVERY draw by construction: the logit maps
the causal/stable band (0,1) onto the whole real line, and the inverse map
expit sends any real phi back into (0,1).
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_TRAIN_DIR = os.path.abspath(os.path.join(_HERE, os.pardir,
                                          "eos_training_curves"))
if os.path.isdir(_TRAIN_DIR) and _TRAIN_DIR not in sys.path:
    sys.path.insert(0, _TRAIN_DIR)

from enum import Enum, auto
import numpy as np
from scipy.special import expit

from eos_common import NB_OVER_N0_GRID, cs2_acceptance_check
from sampling_utils import uniform, log_uniform, beta_scaled

CLASS_NAME = "Class 11: Gaussian-Process sound speed (logit space)"
FILE_PREFIX = "class11_gp_cs2"

_X = NB_OVER_N0_GRID.copy()          # x = n_B / n0 in [0.5, 8]
_L = _X.shape[0]
_D2 = (_X[:, None] - _X[None, :]) ** 2       # (x - x')^2
_DA = np.abs(_X[:, None] - _X[None, :])      # |x - x'|

ETA_MIN, ETA_MAX = 0.15, 3.0     # kernel amplitude eta
ELL_MIN, ELL_MAX = 0.2, 6.0      # correlation length ell  [n_B/n0 units]
CBAR_MIN, CBAR_MAX = 0.02, 0.70  # mean level cbar^2       [c_s^2 units]

PHI_CONFORMAL = float(np.log(0.5))   # logit(1/3) = ln[(1/3)/(2/3)]
NUGGET = 1.0e-8                      # base Cholesky jitter


class Rejection(Enum):
    CHOLESKY_FAILED = auto()
    NUMERICAL = auto()
    ACAUSAL = auto()          # unreachable by construction; kept for the
    UNSTABLE = auto()         # uniform tag mapping of cs2_acceptance_check
    LOW_VARIATION = auto()


def _logit(c):
    return np.log(c / (1.0 - c))


def _kernel(eta, ell, kind):
    if kind == "se":
        return eta * eta * np.exp(-0.5 * _D2 / (ell * ell))
    # Matern-3/2
    s = np.sqrt(3.0) * _DA / ell
    return eta * eta * (1.0 + s) * np.exp(-s)


def _condition_on_point(mean_vec, K, i0, phi0):
    """Exact GP regression update for one noiseless observation
    phi(x_{i0}) = phi0:  m' = m + k0 (phi0 - m_{i0}) / k00,
                         K' = K - k0 k0^T / k00."""
    k0 = K[:, i0]
    k00 = K[i0, i0] + 1.0e-10
    mean_new = mean_vec + k0 * (phi0 - mean_vec[i0]) / k00
    K_new = K - np.outer(k0, k0) / k00
    return mean_new, K_new


def _draw_phi(mean_vec, K, rng):
    """phi = mean + L xi with Sigma = K + jitter*I; escalating jitter."""
    jit = NUGGET
    for _ in range(5):
        try:
            L = np.linalg.cholesky(K + jit * np.eye(_L))
            return mean_vec + L @ rng.standard_normal(_L)
        except np.linalg.LinAlgError:
            jit *= 100.0
    return None

def _const_mean(cbar):
    return np.full(_L, _logit(cbar))


def _linear_mean(c_lo, c_hi):
    p0, p1 = _logit(c_lo), _logit(c_hi)
    return p0 + (p1 - p0) * (_X - _X[0]) / (_X[-1] - _X[0])


def _s_broad_uniform(rng=None):
    return (uniform(ETA_MIN, ETA_MAX, rng=rng),
            uniform(ELL_MIN, ELL_MAX, rng=rng),
            "se",
            _const_mean(uniform(CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


def _s_gorda_conformal(rng=None):
    """Conformal mean cbar^2 = 1/3 (Gorda et al. 2023); O(1) eta, ell."""
    return (uniform(0.5, 2.0, rng=rng),
            log_uniform(0.5, 3.0, rng=rng),
            "se",
            np.full(_L, PHI_CONFORMAL),
            None)


def _s_short_corr(rng=None):
    return (uniform(0.3, 2.0, rng=rng),
            uniform(ELL_MIN, 0.8, rng=rng),
            "se",
            _const_mean(uniform(CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


def _s_long_corr(rng=None):
    return (uniform(0.5, ETA_MAX, rng=rng),
            uniform(2.5, ELL_MAX, rng=rng),
            "se",
            _const_mean(uniform(CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


def _s_small_amp(rng=None):
    return (uniform(ETA_MIN, 0.6, rng=rng),
            uniform(ELL_MIN, 2.5, rng=rng),
            "se",
            _const_mean(uniform(0.05, CBAR_MAX, rng=rng)),
            None)


def _s_large_amp(rng=None):
    return (uniform(1.5, ETA_MAX, rng=rng),
            uniform(0.5, ELL_MAX, rng=rng),
            "se",
            _const_mean(uniform(CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


def _s_matern_broad(rng=None):
    return (uniform(ETA_MIN, ETA_MAX, rng=rng),
            uniform(ELL_MIN, ELL_MAX, rng=rng),
            "m32",
            _const_mean(uniform(CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


def _s_trend_soft_to_conformal(rng=None):
    """Mean rises from a soft low-density level toward ~1/3 at 8 n0."""
    return (uniform(0.3, 1.5, rng=rng),
            uniform(0.5, 4.0, rng=rng),
            "se",
            _linear_mean(uniform(0.02, 0.25, rng=rng),
                         uniform(0.25, 0.45, rng=rng)),
            None)


def _s_trend_rising(rng=None):
    """Mean rises from soft to stiff (monotone-stiffening families)."""
    return (uniform(0.3, 1.5, rng=rng),
            uniform(0.5, 4.0, rng=rng),
            "se",
            _linear_mean(uniform(0.02, 0.20, rng=rng),
                         uniform(0.40, 0.90, rng=rng)),
            None)


def _s_anchored_low(rng=None):
    """Condition the GP on a soft chi-EFT-like value at the first grid
    point (Landry-Essick style conditioning on low-density input)."""
    return (uniform(0.3, 2.0, rng=rng),
            uniform(0.5, 4.0, rng=rng),
            "se",
            _const_mean(uniform(0.10, 0.50, rng=rng)),
            (0, _logit(uniform(0.03, 0.15, rng=rng))))


def _s_beta_centered(rng=None):
    return (beta_scaled(2.0, 2.0, ETA_MIN, ETA_MAX, rng=rng),
            beta_scaled(2.0, 2.0, ELL_MIN, ELL_MAX, rng=rng),
            "se",
            _const_mean(beta_scaled(2.0, 2.0, CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


def _s_log_ell(rng=None):
    return (uniform(ETA_MIN, ETA_MAX, rng=rng),
            log_uniform(ELL_MIN, ELL_MAX, rng=rng),
            "se",
            _const_mean(uniform(CBAR_MIN, CBAR_MAX, rng=rng)),
            None)


STRATEGIES = [
    _s_broad_uniform, _s_gorda_conformal,
    _s_short_corr, _s_long_corr,
    _s_small_amp, _s_large_amp,
    _s_matern_broad,
    _s_trend_soft_to_conformal, _s_trend_rising,
    _s_anchored_low,
    _s_beta_centered, _s_log_ell,
]


def generate_one_sample(rng=None):
    if rng is None:
        from sampling_utils import get_rng
        rng = get_rng()

    strategy = STRATEGIES[rng.integers(len(STRATEGIES))]
    eta, ell, kind, mean_vec, cond = strategy(rng=rng)

    K = _kernel(eta, ell, kind)
    if cond is not None:
        mean_vec, K = _condition_on_point(mean_vec, K, cond[0], cond[1])

    phi = _draw_phi(mean_vec, K, rng)
    if phi is None:
        return None, strategy.__name__, Rejection.CHOLESKY_FAILED

    cs2 = expit(phi)          # in (0,1) for every finite phi -> causal

    tag = cs2_acceptance_check(cs2)
    if tag is not None:
        return None, strategy.__name__, Rejection[tag]

    return cs2, strategy.__name__, None

if __name__ == "__main__":
    from collections import Counter
    from sampling_utils import set_seed

    rng = set_seed(123)
    N_TEST = 400
    ok, rej, strat = [], Counter(), Counter()
    tries = 0
    while len(ok) < N_TEST and tries < 200 * N_TEST:
        tries += 1
        c, s, r = generate_one_sample(rng=rng)
        if c is None:
            rej[r] += 1
        else:
            ok.append(c)
            strat[s] += 1

    arr = np.array(ok)
    assert arr.shape == (N_TEST, _L), f"bad shape {arr.shape}"
    assert np.all(np.isfinite(arr))
    assert arr.min() >= 0.0 and arr.max() <= 1.0, "causality violated!"
    assert arr.std(axis=1).min() >= 0.01, "low-variation curve slipped in"
    print(f"{CLASS_NAME}")
    print(f"  accepted {len(ok)}/{tries} ({len(ok)/tries:.1%})")
    print(f"  c_s^2 in [{arr.min():.3e}, {arr.max():.6f}]  "
          f"min per-curve std = {arr.std(axis=1).min():.4f}")
    for s, c in strat.most_common():
        print(f"    {s:32s}: {c}")
    for r, c in rej.most_common():
        print(f"    REJ {r.name:24s}: {c}")
    print("  smoke test PASSED")
